"""
Data loading utilities for the cross-asset realized-volatility roughness project.

Real data is fetched from the Massive API (MASSIVE_TOKEN environment variable).
Synthetic panels delegate the rough-path simulation to
``src.simulate_rough_paths`` so the project has one canonical implementation.
"""

import os
import numpy as np
import pandas as pd
from typing import Optional


# ---------------------------------------------------------------------------
# Massive API loaders
# ---------------------------------------------------------------------------

def load_equity_intraday(
    ticker: str,
    from_date: str,
    to_date: str,
    timespan: str = "minute",
) -> pd.DataFrame:
    """Load intraday OHLCV data from the Massive API for an equity ticker.

    Parameters
    ----------
    ticker:
        Equity ticker symbol (e.g. ``"SPY"``).
    from_date:
        Start date in ``"YYYY-MM-DD"`` format (inclusive).
    to_date:
        End date in ``"YYYY-MM-DD"`` format (inclusive).
    timespan:
        Bar size passed to the Massive aggregates endpoint (``"minute"``).

    Returns
    -------
    pd.DataFrame
        Columns: ``timestamp`` (ms epoch, int), ``open``, ``high``, ``low``,
        ``close``, ``volume`` (all float64).  Sorted ascending by timestamp.
    """
    from massive.rest import RESTClient

    token = os.environ.get("MASSIVE_TOKEN")
    client = RESTClient(api_key=token)

    bars = list(
        client.list_aggs(
            ticker=ticker,
            multiplier=1,
            timespan=timespan,
            from_=from_date,
            to=to_date,
            sort="asc",
            limit=50_000,
        )
    )

    if not bars:
        return pd.DataFrame(
            columns=["timestamp", "open", "high", "low", "close", "volume"]
        )

    records = [
        {
            "timestamp": b.timestamp,
            "open": b.open,
            "high": b.high,
            "low": b.low,
            "close": b.close,
            "volume": b.volume,
        }
        for b in bars
    ]
    df = pd.DataFrame(records).sort_values("timestamp").reset_index(drop=True)
    df = df.astype(
        {
            "timestamp": "int64",
            "open": "float64",
            "high": "float64",
            "low": "float64",
            "close": "float64",
            "volume": "float64",
        }
    )
    return df


def load_futures_intraday(
    ticker: str,
    from_date: str,
    to_date: str,
) -> pd.DataFrame:
    """Load intraday futures aggregates from the Massive API.

    Parameters
    ----------
    ticker:
        Futures contract ticker (e.g. ``"ESH24"`` for E-mini S&P March 2024).
    from_date:
        Start date filter in ``"YYYY-MM-DD"`` format (inclusive).
    to_date:
        End date filter in ``"YYYY-MM-DD"`` format (inclusive).

    Returns
    -------
    pd.DataFrame
        Columns: ``window_start`` (int, ms epoch), ``open``, ``high``, ``low``,
        ``close``, ``volume``, ``session_end_date`` (str).
    """
    from massive.rest import FuturesClient

    token = os.environ.get("MASSIVE_TOKEN")
    client = FuturesClient(api_key=token)

    bars = list(
        client.list_futures_aggregates(
            ticker=ticker,
            window_start_gte=from_date,
            window_start_lte=to_date,
            sort="asc",
            limit=50_000,
        )
    )

    if not bars:
        return pd.DataFrame(
            columns=[
                "window_start",
                "open",
                "high",
                "low",
                "close",
                "volume",
                "session_end_date",
            ]
        )

    records = [
        {
            "window_start": b.window_start,
            "open": b.open,
            "high": b.high,
            "low": b.low,
            "close": b.close,
            "volume": b.volume,
            "session_end_date": b.session_end_date,
        }
        for b in bars
    ]
    df = pd.DataFrame(records).sort_values("window_start").reset_index(drop=True)
    return df


def generate_synthetic_intraday(
    n_days: int = 252,
    n_bars: int = 390,
    H: float = 0.1,
    kappa: float = 0.01,
    nu: float = 0.5,
    seed: int = 42,
    target_logvol_std: Optional[float] = 1.05,
    target_annualized_vol: Optional[float] = 0.128,
) -> pd.DataFrame:
    """Generate a synthetic daily-fOU / intraday-return panel.

    ``kappa`` is expressed per trading day.  The daily log integrated variance
    is generated by :func:`src.simulate_rough_paths.simulate_fou_log_vol`, with
    a stationary burn-in.  Conditional on that daily variance, exactly
    ``n_bars`` Gaussian intraday returns are simulated, so no return is silently
    discarded at the session open.

    ``target_logvol_std`` optionally rescales the simulated log-variance path
    to the paper's approximately 1.05 daily standard deviation calibration.
    ``target_annualized_vol`` shifts its level so the mean annualized spot
    volatility matches the paper's approximately 12.8% calibration.  Neither
    operation changes the Hurst exponent.
    """
    if n_days < 1 or n_bars < 1:
        raise ValueError("n_days and n_bars must be positive")

    from src.simulate_rough_paths import simulate_fou_log_vol

    log_vol_daily = simulate_fou_log_vol(
        n_days=n_days,
        H=H,
        kappa=kappa,
        nu=nu,
        dt=1.0,
        seed=seed,
    )
    log_vol_daily = log_vol_daily - float(np.mean(log_vol_daily))
    if target_logvol_std is not None:
        current_std = float(np.std(log_vol_daily, ddof=1))
        if current_std > 0.0:
            log_vol_daily *= float(target_logvol_std) / current_std
    if target_annualized_vol is not None:
        if target_annualized_vol <= 0.0:
            raise ValueError("target_annualized_vol must be positive")
        current = float(np.mean(np.exp(log_vol_daily / 2.0)) * np.sqrt(252.0))
        log_vol_daily += 2.0 * np.log(float(target_annualized_vol) / current)

    rng = np.random.default_rng(seed + 1_000_003)
    sigma_per_bar = np.exp(log_vol_daily / 2.0) / np.sqrt(float(n_bars))
    returns_2d = rng.standard_normal((n_days, n_bars)) * sigma_per_bar[:, None]

    # Each row is the close of one synthetic minute interval; return_[d, i]
    # is the interval return ending at that row.  The session is reset to zero
    # every day, so overnight returns never enter daily RV.
    log_price_2d = np.cumsum(returns_2d, axis=1)

    base_date = pd.Timestamp("2010-01-04")
    trading_dates = pd.bdate_range(start=base_date, periods=n_days)
    return pd.DataFrame(
        {
            "date": np.repeat(trading_dates, n_bars),
            "bar_idx": np.tile(np.arange(n_bars, dtype=np.int32), n_days),
            "log_price": log_price_2d.ravel(),
            "return_": returns_2d.ravel(),
            "latent_log_iv": np.repeat(log_vol_daily, n_bars),
        }
    )
